# Generated by Django 5.2.6 on 2025-11-23 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom unique de la formation', max_length=200, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la formation')),
                ('duree_estimee', models.PositiveIntegerField(help_text='Durée standard en heures (doit être positif)')),
                ('est_actif', models.BooleanField(default=True, help_text='Indique si la formation est active et visible dans le catalogue')),
            ],
            options={
                'verbose_name': 'Modèle de Formation',
                'verbose_name_plural': 'Catalogue Permanent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='FormationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(help_text='Date et heure de début de la session')),
                ('date_fin', models.DateTimeField(blank=True, help_text='Date et heure de fin de la session (facultatif)', null=True)),
                ('statut', models.CharField(choices=[('PLAN', 'Planifiée'), ('ENCOURS', 'En Cours'), ('TERMINEE', 'Terminée')], default='PLAN', help_text='Statut actuel de la session', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formateur', models.ForeignKey(blank=True, help_text='Formateur (rôle intern)', limit_choices_to={'role': 'intern'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_dirigees', to=settings.AUTH_USER_MODEL)),
                ('formation_type', models.ForeignKey(help_text='Formation du catalogue associée', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training_management.formationtype')),
            ],
            options={
                'verbose_name': 'Session de Formation',
                'verbose_name_plural': 'Sessions de Formation',
                'ordering': ['date_debut'],
            },
        ),
        migrations.CreateModel(
            name='SupportFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(help_text='Fichier support (PDF, PPT, DOC, etc.)', upload_to='supports_formation/%Y/%m/%d/')),
                ('titre', models.CharField(help_text='Titre du support', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description du support')),
                ('type_support', models.CharField(choices=[('PDF', 'Document PDF'), ('PPT', 'Présentation PowerPoint'), ('DOC', 'Document Word'), ('EXCEL', 'Fichier Excel'), ('VIDEO', 'Vidéo'), ('AUTRE', 'Autre')], default='PDF', help_text='Type de support', max_length=50)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('formation_type', models.ForeignKey(help_text='Formation à laquelle ce support appartient', on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='training_management.formationtype')),
            ],
            options={
                'verbose_name': 'Support de Formation',
                'verbose_name_plural': 'Supports de Formation',
                'ordering': ['formation_type', 'titre'],
            },
        ),
    ]
