# Generated by Django 5.2.5 on 2025-09-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='profile complete'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_profile_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last profile reminder'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_completion_reminders',
            field=models.PositiveIntegerField(default=0, verbose_name='profile reminders'),
        ),
    ]
