# Generated by Django 5.2.6 on 2025-11-26 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Titre de l'annonce", max_length=200, verbose_name='titre')),
                ('content', models.TextField(help_text="Contenu détaillé de l'annonce", verbose_name='contenu')),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now, help_text="Date et heure de publication de l'annonce", verbose_name='date de publication')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', help_text="Niveau de priorité de l'annonce", max_length=10, verbose_name='priorité')),
                ('is_active', models.BooleanField(default=True, help_text="Indique si l'annonce est visible sur la plateforme", verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date de modification')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_created', to=settings.AUTH_USER_MODEL, verbose_name='créé par')),
            ],
            options={
                'verbose_name': 'annonce',
                'verbose_name_plural': 'annonces',
                'ordering': ['-publication_date', '-priority'],
                'indexes': [models.Index(fields=['publication_date', 'is_active'], name='communicati_publica_f4befc_idx'), models.Index(fields=['priority', 'is_active'], name='communicati_priorit_5df6f0_idx'), models.Index(fields=['is_active'], name='communicati_is_acti_7dd704_idx')],
            },
        ),
    ]
