# Generated by Django 5.2.6 on 2025-11-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre unique du thème de stage', max_length=200, unique=True, verbose_name='titre')),
                ('description', models.TextField(help_text='Description détaillée du thème', max_length=1000, verbose_name='description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('assignment_date', models.DateTimeField(blank=True, null=True, verbose_name="date d'attribution")),
                ('status', models.CharField(choices=[('non_attribue', 'Non attribué'), ('attribue', 'Attribué')], default='non_attribue', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'thème',
                'verbose_name_plural': 'thèmes',
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['status'], name='internship__status_a8524e_idx'), models.Index(fields=['created_date'], name='internship__created_743a4c_idx'), models.Index(fields=['status', 'is_active'], name='internship__status_ccdfde_idx')],
            },
        ),
    ]
